# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: neck
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - base_to_wheel_left_joint
    - base_to_wheel_right_joint
    - joint_neck_1
  sim_control_mode: 1  # 0: position, 1: velocity

# Publish all joint states
# Creates the h/joint_states topic necessary in ROS
# neck:7888888888888888888888iiiiiiiiiiii
  


controller_manager_ns: controller_manager  
controller_list:
  - name: neck/neck_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - joint_neck_1

neck:
  neck_controller:
    type: position_controllers/JointPositionController
    joint: joint_neck_1
    pid: {p: 100.0, i: 0.01, d: 10.0}

  joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50
