# obstacle_range: 3.5
# raytrace_range: 4.0
# robot_radius: 0.3 #0.165
# inflation_radius: 0.2
# max_obstacle_height: 1.6
# min_obstacle_height: 0.0
# observation_sources: scan
# scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true, expected_update_rate: 0}

obstacle_range: 2.5
raytrace_range: 3.0
robot_radius: 0.165
inflation_radius: 0.3   #min distance from obstacle
max_obstacle_height: 1.6
min_obstacle_height: 0.0
observation_sources: scan
scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true, expected_update_rate: 0}

